'use strict';

const ExceptionConst = {
    ErrorCode: {
        ERROR_SANITIZER: 'ERROR_SANITIZER',
        ERROR_NOT_IMPLEMENTED: 'ERROR_NOT_IMPLEMENTED',
        ERROR_UNIQUE_CONSTRAINT: 'ERROR_UNIQUE_CONSTRAINT',
        ERROR_INSTANCE_ALREADY_CREATED: 'ERROR_INSTANCE_ALREADY_CREATED',
        ERROR_NOT_INITIALIZED: 'ERROR_NOT_INITIALIZED'
    }
};

module.exports = ExceptionConst;
